CREATE TABLE ATHLETE_SCH.USERS (
    ID UUID NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_ON TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL,
    UPDATED_ON TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    USERNAME VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    BIRTH_DATE DATE,
    PASSWORD VARCHAR(250) NOT NULL,

    PRIMARY KEY (ID)
);

CREATE TABLE ATHLETE_SCH.ROLES (
    ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    PAYLOAD TEXT,

    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ROLES FOREIGN KEY (USER_ID) REFERENCES ATHLETE_SCH.USERS (ID) ON DELETE CASCADE
);

CREATE INDEX USERS_USERNAME_IDX ON ATHLETE_SCH.USERS (USERNAME);
CREATE INDEX USERS_EMAIL_IDX ON ATHLETE_SCH.USERS (EMAIL);
CREATE INDEX ROLES_USERID_IDX ON ATHLETE_SCH.ROLES (USER_ID);